### PR TITLE
V0.1.4 Release

### PR DESCRIPTION
**Pull request by tkent**
Candidate release branch for the v0.1.4 release of the xetusoss-archiva chart.

This includes:

1. The changes from #4
2. A fix for #5 
3. Support for the v1.14+ `networking.k8s.io/v1beta1` in the ingress resource.

### CODE REVIEW

**Comment by tkent** [comment]
@Jonathan-Eid  Can you please confirm this branch works for you in Kubernetes v1.17?  Thank you!

**Comment by tkent** [comment]
@Jonathan-Eid  /bump? If I don't hear from you by Tuesday, we're going to move ahead since we're pretty confident it works based on testing on v1.14

**Comment by Jonathan-Eid** [comment]
This branch works, thank you so much.

**Review by tmeneau — APPROVED** [review]
These changes look good! Thanks @tkent for making these changes, and thanks @Jonathan-Eid and @trayla for the bug reports!

**Pull request merged**
